version: '3.7'

services:
  blog_postgredb:
    image: postgres:13
    container_name: blog_postgredb
    volumes:
      - blog_postgredb:/C/Program Files/PostgreSQL/13/data
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - network

volumes:
  blog_postgredb:
    external: true
networks:
  network:
    external: true